### ISSUE TITLE
Błąd przy ładowaniu WMSów w QGIS

### ISSUE THREAD

**Issue by pavaos** [cartomatic/hgis#11]
Niestety w QGIS 2.18 każda próba załadowania wmsów z hgis kończy się komunikatem "Awaria przy zrzucie" i zamknięciem programu. Próbowałem różnych opcji (także uwzględniając kwestie poruszone w wątku: https://github.com/cartomatic/hgis/issues/9. Robiłem to na kilku komputerach (z Win 7 i 8, jeśli ma to jakieś znaczenie), na każdym dzieje się to samo . Czy da się coś z tym zrobić?

**Comment by mika666** [comment]
u mnie działa... ;) 
na poważnie, [instrukcja](http://hgis.cartomatic.pl/post/hgis-wms-w-qgis) zdaje się wciąż być aktualna.
Poniżej 'wyciąg'
![image](https://cloud.githubusercontent.com/assets/712528/20767425/82782a1a-b73a-11e6-85ce-d39cb27c8030.png)
![image](https://cloud.githubusercontent.com/assets/712528/20767454/9a0de426-b73a-11e6-9ea4-6c8ce986320d.png)

Co prawda QGIS 2.2.0, ale nie sądzę, żeby coś się miało jakoś drastycznie zmienić. nasze serwisy mają ograniczenia w wielkości serwowanych rastrów - max to 256x256. Zwróć na to uwagę.

**Comment by pavaos** [comment]
No, niestety, wszystko to robię. Zarówno jeśli chodzi o "Ignore GetMap..." jak i rozmiar kafla. Kurcze, nawet nazwę usługi już wpisywałem taką samą (w sensie wms(at)hgis...), choć to oczwiście nie może mieć żadnego znaczenia. Po prostu nie działa.

![image](https://cloud.githubusercontent.com/assets/24255801/20777176/91e0a43e-b765-11e6-92de-f2283ba2d3ed.png)

**Comment by mika666** [comment]
na starszych windowsach nie sprawdzę, bo nie mam pod ręką obrazu 7/8.
sprawdź może nowszego quantuma. nie sądzę, żebyśmy byli takimi hakierami, żeby zarżnąć qgisa odpowiedzią z serwera WMS ;)
Jak masz chęć zainstaluj fiddlera i zobacz jakie zapytania idą do a jakie odpowiedzi idą z serwera, zanim ci się qgis usmaży.

**Comment by pavaos** [comment]
Ok, wszystko się wyjaśniło. Co prawda nowszego quantuma nie mogłem zainstalować, bo 2.18 (Las Palmas) jest najnowszy ;), ale zainstalowałem poprzednią wersję 2.14 (Essen) i wszystko śmiga. Trzeba zatem męczyć qgisowców o bugfixa do 2.18. Dzięki.

**Comment by mika666** [comment]
najs
